Patch release v2.3.3
Lightning-AI/pytorch-lightning pull request #20051
Opened 2024-07-05 12:56 UTC by awaelchli

2024-07-05 13:25 UTC, Borda requested changes
May need to check how the code removal was done and but this large code change shall be at leat feature release not bug-fix...

2024-07-05 14:03 UTC, justusschock approved these changes

2024-07-05 14:04 UTC, justusschock commented
@Borda this only changes the lightning_app code which was never under proper semantic versioning

2024-07-05 14:58 UTC, Borda commented
> @Borda this only changes the lightning_app code which was never under proper semantic versioning

True but changes and nuke it very different especially with respect to `lightning` package

2024-07-08 09:16 UTC, Borda commented
lets add #20059

2024-07-08 11:42 UTC, Borda approved these changes

2024-07-08 13:02 UTC, lantiga approved these changes

2024-07-08 13:05 UTC, merged