Fix LightningCLI saving hyperparameters breaking change
Lightning-AI/pytorch-lightning pull request #20068
Opened 2024-07-10 09:03 UTC by mauvilsa

## What does this PR do?

Changes the `LightningCLI`'s `load_from_checkpoint` support such that the hparams are not saved with the `class_path` and `init_args` structure, since this constitutes a breaking change which we failed to notice in #18105.

Fixes #19977

<details>
  <summary><b>Before submitting</b></summary>

- Was this **discussed/agreed** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- Did you make sure to **update the documentation** with your changes? (if necessary)
- Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- Did you list all the **breaking changes** introduced by this pull request?
- Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

</details>

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

<details>
  <summary>Reviewer checklist</summary>

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

</details>

2024-07-10 11:44 UTC, adamjstewart requested changes
Thanks for the quick fix @mauvilsa. ~This seems very specific to `init_args` and ignores `dict_kwargs`.~ I also seem to be missing many class parameters with default values that are not listed in the YAML file, and/or optional values that default to None.

EDIT: It's possible no special handling is needed for `dict_kwargs`.

2024-07-10 11:58 UTC, adamjstewart commented
Steps to reproduce are identical to https://github.com/Lightning-AI/pytorch-lightning/issues/19977#issuecomment-2214014470, but replace `model.py` with:
```python
from lightning.pytorch import LightningModule


class Model(LightningModule):
    def __init__(self, learning_rate, step_size=None):
        super().__init__()
        self.save_hyperparameters()
        assert 'learning_rate' in self.hparams
        assert 'step_size' in self.hparams

    def training_step(*args):
        pass

    def configure_optimizers(*args):
        pass
```
The code will fail because `step_size` is not defined in `self.hparams`.

2024-07-10 16:16 UTC, mauvilsa commented
> I also seem to be missing many class parameters with default values that are not listed in the YAML file, and/or optional values that default to None.

Indeed, there was a bug.

> It's possible no special handling is needed for dict_kwargs.

It is needed. It is now fixed and I added a new unit test based on your code snippet which includes `dict_kwargs`.

@adamjstewart please check again.

2024-07-10 17:37 UTC, adamjstewart approved these changes
Passes all TorchGeo tests now, thanks for the quick fix!

2024-07-10 23:44 UTC, awaelchli approved these changes
Thank you @mauvilsa, very appreciated!

2024-07-11 07:21 UTC, mauvilsa commented on src/lightning/pytorch/cli.py
> +                "_class_path": hparams["class_path"],
Added a comment.

2024-07-11 10:38 UTC, merged

2024-07-11 10:38 UTC, awaelchli commented
Thanks @mauvilsa @adamjstewart for the help here 🚀