Update (ci): github action's artifact upgrade due to EOL for versions less than 4
Lightning-AI/pytorch-lightning pull request #20500
Opened 2024-12-16 18:32 UTC by alleeclark

## What does this PR do?

Updates Github workflows to use the latest version of artifacts for downloading and uploading

Fixes #\<issue_number>

<details>
  <summary><b>Before submitting</b></summary>

- Was this **discussed/agreed** via a GitHub issue? (not for typos and docs)
- [ ] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [ ] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- Did you make sure to **update the documentation** with your changes? (if necessary)
- Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- Did you list all the **breaking changes** introduced by this pull request?
- Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

</details>

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

<details>
  <summary>Reviewer checklist</summary>

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

</details>

2024-12-16 19:56 UTC, alleeclark commented on .github/workflows/_build-packages.yml
> +          overwrite: true
Artifacts are uploaded in the init job (line 28) as a placeholder, therefore we need to overwrite them. See https://github.com/Lightning-AI/pytorch-lightning/actions/runs/12359005253/job/34490799219#step:8:22

2024-12-17 01:05 UTC, alleeclark commented on docs/source-pytorch/conf.py
> +    "https://developer.habana.ai", # returns 403 error but redirects to intel.com documentation
[some habana.ai  sub domains route to intel](https://habana.ai/press/intel-acquires-artificial-intelligence-chipmaker-habana-labs/). For some reason this just started causing 403 errors.

2024-12-17 01:06 UTC, alleeclark commented on docs/source-pytorch/conf.py
> +    "https://developer.habana.ai", # returns 403 error but redirects to intel.com documentation
https://developer.habana.ai redirects to https://www.intel.com/content/www/us/en/developer/platform/gaudi/overview.html

2024-12-17 02:46 UTC, Borda requested changes
The direction is good, it just needs some more work with adding patterns and making unique uploads... 
pls, have look what I gave done earlier this week for shared utils project: https://github.com/Lightning-AI/utilities/pull/344

2024-12-17 10:16 UTC, Borda commented on .github/workflows/ci-pkg-install.yml
> +          merge-multiple: true
```suggestion
```

2024-12-17 10:17 UTC, Borda commented on .github/workflows/docs-build.yml
> +          merge-multiple: true
```suggestion
```

2024-12-17 10:17 UTC, Borda commented on .github/workflows/release-pkg.yml
> +          merge-multiple: true
```suggestion
```

2024-12-17 10:18 UTC, Borda commented on .github/workflows/release-pkg.yml
> +          merge-multiple: true
```suggestion
```

2024-12-17 10:18 UTC, Borda commented on .github/workflows/release-pkg.yml
> +          merge-multiple: true
```suggestion
```

2024-12-17 10:19 UTC, Borda approved these changes

2024-12-17 13:07 UTC, alleeclark commented
> The direction is good, it just needs some more work with adding patterns and making unique uploads... pls, have look what I gave done earlier this week for shared utils project: [Lightning-AI/utilities#344](https://github.com/Lightning-AI/utilities/pull/344)

Thanks. I reviewed the changes.

2024-12-17 13:08 UTC, merged